# Generated by Django 4.0.3 on 2022-03-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='codes',
            name='code',
            field=models.TextField(),
        ),
    ]
